version: '3.0'
services:
  db:
    image: postgres:13.1-alpine
    hostname: ${POSTGRES_HOSTNAME:-db}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: food_find
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
  web:
    build: .
    command: bash -c "rails assets:precompile && ./bin/webpack && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: serve
    labels:
      - traefik.enable=true
      - traefik.http.routers.${ROUTER_NAME:-food_find}.rule=Host(`${DOMAIN:?err}`)
      - traefik.http.routers.${ROUTER_NAME:-food_find}.tls.certresolver=letsencrypt
volumes:
  db-data:
