version: '3.0'
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: food_find
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  web:
    build: .
    command: bash -c "rails assets:precompile && ./bin/webpack && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: serve
volumes:
  db-data:
